### ISSUE TITLE
Support Verdaccio 5

### ISSUE THREAD

**Issue by kimxogus** [n4bb12/verdaccio-github-oauth-ui#127]
#### Is your feature request related to a problem? Please describe.

With `verdaccio@5.0.1`, it fails to startup(like log below). It seems verdaccio-github-oauth-ui is not compatible with `verdaccio@5`.
Also, [`url_prefix` behavior changed](https://verdaccio.org/blog/2021/04/14/verdaccio-5-migration-guide#url_prefix-improved-behavior).

```plain
{"level":40,"time":1618542664227,"pid":9,"hostname":"npm-registry-verdaccio-74c467f7cd-d9ld7","file":"/verdaccio/conf/config.yaml","msg":"config file  - @{file}"}
{"level":40,"time":1618542664449,"pid":9,"hostname":"npm-registry-verdaccio-74c467f7cd-d9ld7","content":"aws-s3-storage","prefix":"verdaccio","msg":"Plugin successfully loaded: @{prefix}-@{content}"}
[github-oauth-ui] Version: verdaccio-github-oauth-ui@2.4.0
[github-oauth-ui] Proxy config: {"HTTP_PROXY":null,"HTTPS_PROXY":null,"NO_PROXY":null}
{"level":40,"time":1618542665458,"pid":9,"hostname":"npm-registry-verdaccio-74c467f7cd-d9ld7","content":"github-oauth-ui","prefix":"verdaccio","msg":"Plugin successfully loaded: @{prefix}-@{content}"}
{"level":40,"time":1618542665483,"pid":9,"hostname":"npm-registry-verdaccio-74c467f7cd-d9ld7","content":"audit","prefix":"verdaccio","msg":"Plugin successfully loaded: @{prefix}-@{content}"}
[github-oauth-ui] Proxy config: {"HTTP_PROXY":null,"HTTPS_PROXY":null,"NO_PROXY":null}
{"level":40,"time":1618542665484,"pid":9,"hostname":"npm-registry-verdaccio-74c467f7cd-d9ld7","content":"github-oauth-ui","prefix":"verdaccio","msg":"Plugin successfully loaded: @{prefix}-@{content}"}
{"level":30,"time":1618542665485,"pid":9,"hostname":"npm-registry-verdaccio-74c467f7cd-d9ld7","msg":"unhandledRejection caught"}
{"level":50,"time":1618542665485,"pid":9,"hostname":"npm-registry-verdaccio-74c467f7cd-d9ld7","errno":-2,"syscall":"open","code":"ENOENT","path":"/opt/verdaccio/node_modules/verdaccio-github-oauth-ui/dist/public/verdaccio-5.css","stack":"Error: ENOENT: no such file or directory, open '/opt/verdaccio/node_modules/verdaccio-github-oauth-ui/dist/public/verdaccio-5.css'\n    at Object.openSync (fs.js:476:3)\n    at Object.readFileSync (fs.js:377:35)\n    at new PatchHtml (/opt/verdaccio/node_modules/verdaccio-github-oauth-ui/dist/server.js:2362:38)\n    at Plugin.register_middlewares (/opt/verdaccio/node_modules/verdaccio-github-oauth-ui/dist/server.js:2645:54)\n    at /opt/verdaccio/build/api/index.js:72:12\n    at Array.forEach (<anonymous>)\n    at defineAPI (/opt/verdaccio/build/api/index.js:71:11)\n    at _default (/opt/verdaccio/build/api/index.js:124:10)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","type":"Error","msg":"error caused exit"}
{"level":30,"time":1618542665486,"pid":9,"hostname":"npm-registry-verdaccio-74c467f7cd-d9ld7","msg":"exit caught"}
```

**Comment by n4bb12** [comment]
Released in https://github.com/n4bb12/verdaccio-github-oauth-ui/releases/tag/3.0.0
